// packages/demo-jest/src/components/react/link/index.tsx
import React, { useState, useCallback } from 'react';
import { ILinkProps } from './interface';

enum STATUS {
    HOVERED = 'hovered',
    NORMAL = 'normal',
}

const Link: React.FC<ILinkProps> = props => {
    const [className, setClassName] = useState(STATUS.NORMAL);
    const { page = '#', children } = props;

    const onMouseEnter = useCallback(() => setClassName(STATUS.HOVERED), []);

    const onMouseLeave = useCallback(() => setClassName(STATUS.NORMAL), []);

    return (
        <a
            className={className}
            href={page}
            onMouseEnter={onMouseEnter}
            onMouseLeave={onMouseLeave}
        >
            {children}
        </a>
    )
};

export default Link;

// packages/demo-jest/src/components/vue/link/link.vue
<template>
    <a :class="className" :href="page" @mouseenter="onMouseEnter" @mouseleave="onMouseLeave">
        <slot></slot>
    </a>
</template>
<script lang="ts">
import { Component, Vue, Prop } from "vue-property-decorator";

enum STATUS {
    HOVERED = 'hovered',
    NORMAL = 'normal',
}

@Component
export default class Link extends Vue {
    className: STATUS = STATUS.NORMAL;

    @Prop({
        type: String,
        default: '#',
    })
    page!: string;

    onMouseEnter(): void {
        this.className = STATUS.HOVERED;
    }

    onMouseLeave(): void {
        this.className = STATUS.NORMAL;
    }
}
</script>
<style lang="scss" scoped>
a {
    text-decoration: none;
}
</style>
